import React from 'react';

export const STATUS = {
    ORDER_STATUS_DONE: 1,
    ORDER_STATUS_ACCEPT: 2,
    ORDER_STATUS_SEPARATION: 3,
    ORDER_STATUS_DELIVERING: 4,
    ORDER_STATUS_DELIVERED: 5,
    ORDER_STATUS_REJECT: 6,
    ORDER_STATUS_CANCELED: 7,
    ORDER_STATUS_ERROR: 8,
}